---
- name: Test Petclinic project
- hosts: VMs
  become: yes
  tasks:
    - name: Clone my repository from GitHub
      git:
        repo: https://github.com/Alkaponees/Diploma.git
        dest: /home/user/repos/
        clone: yes
        updated: yes

